name: React Ci Pipeline

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: app

      - name: Run ESLint
        run: npm run lint
        working-directory: app

      - name: Run Unit Tests
        run: npm test -- --watchAll=false --ci
        working-directory: app